name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMTEMVER_GITHUB_TOKEN }}

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.SEMTEMVER_GITHUB_TOKEN }}
          PyPI_token: ${{ secrets.PyPI_TOKEN }}
